name: Print Repo Info


on:
  push:
    paths:
      - student_note.md

  jobs:
    stuInfo:
      runs-on: ubuntu-latest
      env:
        REPO_NAME: ${{ github.repository }}
        STUDENT_USERNAME: ${{ github.actor }}
      steps:
        - name: Print environment variables
          run:  |
            echo "Repository Name: $REPO_NAME"
            echo "Student Username: $STUDENT_USERNAME"
                
