name: Print Repo and Student Info

on:
  push:
    paths:
      - student_note.md  # Only trigger if this file changes

jobs:
  print-info:
    runs-on: ubuntu-latest
    env:
      STUDENT_USERNAME: ${{ github.actor }}
      REPO_NAME: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print repo name
        run: echo "Repository: $REPO_NAME"

      - name: Print student username
        run: echo "Student Username: $STUDENT_USERNAME"
